### ISSUE TITLE
Components loading failing with using the content module

### ISSUE THREAD

**Issue by kalinichenko88** [nuxt/components#223]
**Describe the bug**

In dev mode all works. But `nuxt generate` and `nuxt build` failed with the error

- If a component is registered in the page it will work fine
- issue with autoloaded components only
- I solved this issue for myself. I added in package.json "@nuxt/components": "2.1.8"

**To Reproduce**
1. Clone repository `https://github.com/kalinichenko88/nuxt-components-bug`
2. Run `npm i`
3. Run `npm run generate`
4. See error `Error: render function or template not defined in component: tutorial`

**Comment by chrispreisler** [comment]
I also experienced the same bug, when using the plugin with the <component> component. I stepped back to 2.1.8. There I don't have any problems. It is also only happening, when building/generating the page.

**Comment by rchl** [comment]
I'm using undocumented `components: { loader: true }` in my nuxt-config and with that the https://github.com/nuxt/components/releases/tag/v2.2.0 appears to have a breaking change. Most likely due to:
 - explicit async loading (#212) (5adefb9)

**Comment by chrispreisler** [comment]
Yes, I also think, that this feature may be a breaking change for dynamic components. I also tried adding async to the filename, but this doesn't work either.

**Comment by rchl** [comment]
I'm getting errors like: `ERROR  render function or template not defined in component: foo-bar-v-2` with the new version.

What would be a way to get things to work for someone who uses `loader: true` (apart from downgrading)?

**Comment by pi0** [comment]
Thanks for reproduction @kalinichenko88. Just remove `package-lock.json` (or `yarn.lock`) and reinstall. The issue is fixed in [v2.2.1](https://github.com/nuxt/components/releases/tag/v2.2.1).

**Comment by ibdf** [comment]
I am still having this issue, but it fails without an error. The vue component in the .md files load perfectly in the dev environment but not when using generate or build. I am on:

"@nuxt/content": "^1.11.1",
"nuxt": "^2.14.12"

components: true
