### ISSUE TITLE
No auto import of components after 'nuxt generate'

### ISSUE THREAD

**Issue by m7rlin** [nuxt/components#224]
``**Describe the bug**
When use 'components: true' and then import a component on my page it is working just fine on 'dev' but after running 'generate' command and starting 'start' the web server I don't see any of my components that should be auto imported.

**To Reproduce**
1. Clone repository 'https://github.com/m7rlin/nuxt-auto-import-components'
2. Run 'npm run generate'
3. Then run 'npm run start'
4. Open the server on 'http://localhost:3000' and see that the '@/components/webblocks/Cards.vue' component is not there

**Expected behavior**
Auto imported components should be visible on production.

**Screenshots**
On production now:
![image](https://user-images.githubusercontent.com/11756007/129464049-da99d506-42c1-43aa-9ac4-159ae71d0a20.png)

How it should look like:
![image](https://user-images.githubusercontent.com/11756007/129464032-ef2ffdb3-d726-4316-9fcb-8457e74b2950.png)

**Additional context**
When I import the components the normal way, they are visible on production.

![image](https://user-images.githubusercontent.com/11756007/129464089-c165b8dc-9b56-4080-9fa4-4955d6cab0f4.png)

EDIT:
If I do this on package.json (npm)

```
...
"scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate",
    "lint:js": "eslint --ext \".js,.vue\" --ignore-path .gitignore .",
    "lint": "npm run lint:js",
    "preinstall": "npx npm-force-resolutions"
  },
...
},
  "resolutions": {
    "@nuxt/components": "2.1.8"
  }
...
```
It seems working just fine.
EDIT:
I found that downgrading "nuxt components" to v2.1.8 fix the problem.

"@nuxt/components": "2.1.8"

**Comment by kurashina-design** [comment]
SSR mode, that is, yarn build & yarn start, also leads to no auto import.
I tried to npx create-nuxt-app today.

Manual import worked.

**Comment by richardeschloss** [comment]
I have the same issue with `nuxt build`. No auto-import of components.

**Comment by pi0** [comment]
The regression is fixed in [components@2.2.1](https://github.com/nuxt/components/releases/tag/v2.2.1). Just remove `yarn.lock`/`package.lock.json` and reinstall dependencies.

**Comment by command-tab** [comment]
@pi0 Perhaps related to https://github.com/nuxt/components/issues/204, I'm still encountering this issue with nuxt 2.15.8 and nuxt/components 2.2.1 installed (verified in both my `yarn.lock` file and on disk in `node_modules/@nuxt/components/package.json`).

However, there's a twist: If I list several scoped components in my `nuxt.config.js` file and instantiate them side-by-side in a `.vue` file, _all_ of them appear when running `nuxt` in development, but only _some_ of them appear when doing `nuxt build` and `nuxt start`. When a inspect those that don't appear in the Chrome devtools, I see their component names, not the HTML elements they're supposed to render. Is there some critical detail or `package.json` field that needs to be in place for scoped components to load when doing a `nuxt build`? They're all pretty simple CommonJS modules with component names 🤔

**Comment by pi0** [comment]
Hi @command-tab. Can you probably check `.nuxt/components/index.js` after `nuxt build` command? There should be expected exports as loader fallback. Also if you can make a reproduction that is similar to you setup I could check it out :)

**Comment by command-tab** [comment]
When I look in `.nuxt/components/index.js` (for a `nuxt build`), I do see the expected exports, but only some of those listed actual render (no errors when they don't — they just leave their custom HTML tags in place). Weird! I'll see if I can put together a minimal, clone-able repro repo.
